project:
  root: com.example.demo
  name: monsters
database:
  name: monsters
  driver: com.mysql.cj.jdbc.Driver
file:
  path: ./monsters/back-end/file
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://140.131.114.242:3306/111- monsters?useSSL=false&serverTimezone=Asia/Taipei
    username: monsters
    password: MONsters@ntub108
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    show-sql: false
    generate-ddl: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: none
    properties:
      hibernate:
        dialect: ${spring.jpa.database-platform}
        hbm2ddl:
          auto: ${spring.jpa.hibernate.ddl-auto}
        show_sql: ${spring.jpa.show-sql}
        format_sql: ${spring.jpa.show-sql}
    http:
      multipart:
        maxFileSize: 100Mb
        maxRequestSize: 100Mb
server:
  port: 8080
  delegate-port: 8080
  servlet:
    encoding:
      charset: UTF-8
  cores:
    origins: http://localhost:8080
    http-methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'PATCH'
      - 'DELETE'
      - 'OPTIONS'
    http-headers:
      - '*'
    export-http-headers:
      - 'X-Auth-Token'
